import { useState } from "react";
import { Send, Sparkles } from "lucide-react";

import { askCopilot } from "../engine/copilot";
import { useStore } from "../lib/store";
import type { CopilotAnswer } from "../types";
import { Button, Card } from "./ui";

const SUGGESTED = [
  "Where is the money now?",
  "Why did this payment fail?",
  "Was the agent authorized to make this purchase?",
  "Why was this rail selected?",
  "Which transactions remain unreconciled?",
  "What's pending approval right now?",
  "What should the operations team do next?",
];

export default function Copilot() {
  const {
    transactions,
    incidents,
    agents,
    approvalTasks,
    auditLog,
  } = useStore();

  const [input, setInput] = useState("");

  const [thread, setThread] = useState<
    CopilotAnswer[]
  >([]);

  function ask(question: string) {
    if (!question.trim()) {
      return;
    }

    const answer = askCopilot(question, {
      transactions,
      incidents,
      agents,
      approvalTasks,
      auditLog,
    });

    setThread((previous) => [
      ...previous,
      answer,
    ]);

    setInput("");
  }

  return (
    <div className="flex h-full flex-col space-y-5">
      <div>
        <h1 className="text-xl font-semibold">
          Investigation Copilot
        </h1>

        <p className="mt-1 text-sm text-[var(--color-ink-dim)]">
          Ask questions in plain language. Answers are
          generated by reasoning over the actual
          transaction, routing, incident, approval, and
          audit-event data — reference a transaction ID,
          or ask about the latest payment.
        </p>
      </div>

      {thread.length === 0 && (
        <Card>
          <div className="mb-3 flex items-center gap-2 text-sm text-[var(--color-ink-dim)]">
            <Sparkles className="h-4 w-4 text-[var(--color-accent)]" />

            Try asking:
          </div>

          <div className="flex flex-wrap gap-2">
            {SUGGESTED.map((suggestion) => (
              <button
                key={suggestion}
                type="button"
                onClick={() =>
                  ask(suggestion)
                }
                className="rounded-full border border-[var(--color-border-bright)] bg-[var(--color-surface-raised)] px-3 py-1.5 text-xs text-[var(--color-ink-dim)] hover:border-[var(--color-accent)]/50 hover:text-[var(--color-ink)]"
              >
                {suggestion}
              </button>
            ))}
          </div>
        </Card>
      )}

      <div className="flex-1 space-y-3 overflow-y-auto">
        {thread.map((answer, index) => (
          <div
            key={`${answer.question}-${index}`}
            className="space-y-2"
          >
            <div className="flex justify-end">
              <div className="max-w-[80%] rounded-lg bg-[var(--color-accent-dim)] px-3.5 py-2 text-sm text-[var(--color-accent)]">
                {answer.question}
              </div>
            </div>

            <div className="flex justify-start">
              <div className="max-w-[80%] rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] px-3.5 py-2.5 text-sm text-[var(--color-ink)]">
                {answer.answer}

                {answer.citedEventIds.length >
                  0 && (
                  <div className="mt-2 flex flex-wrap gap-1.5 border-t border-[var(--color-border)] pt-2">
                    {answer.citedEventIds.map(
                      (eventId) => (
                        <span
                          key={eventId}
                          className="rounded border border-[var(--color-border-bright)] px-1.5 py-0.5 font-mono-num text-[10px] text-[var(--color-ink-faint)]"
                        >
                          {eventId}
                        </span>
                      ),
                    )}
                  </div>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="flex gap-2">
        <input
          value={input}
          onChange={(event) =>
            setInput(event.target.value)
          }
          onKeyDown={(event) => {
            if (event.key === "Enter") {
              ask(input);
            }
          }}
          placeholder="Ask about a transaction, rail decision, or exposure..."
          className="flex-1 rounded-md border border-[var(--color-border-bright)] bg-[var(--color-surface-raised)] px-3.5 py-2.5 text-sm outline-none focus:border-[var(--color-accent)]"
        />

        <Button
          onClick={() => ask(input)}
        >
          <Send className="h-4 w-4" />
        </Button>
      </div>
    </div>
  );
}
